# Centralised hyper-parameters ---------------------------------
seed: 42
device: cuda

data:
  root: data/VIPPrint-Dataset                         # expected folder after download
  patch_dir: data/VIPPrint_patches            # auto-created by preprocess script
  input_size: 299
  batch_size: 64
  num_workers: 8
  train_split: 0.75         # split by DIGITAL IMAGE ID to avoid leakage
  val_split: 0.10

model:
  name: xception41_preact                      # timm id
  pretrained: false                            # train from scratch
  num_classes: 8

optim:
  epochs: 80
  lr: 0.001
  weight_decay: 1e-4
  scheduler: cosine
  label_smoothing: 0.1

logging:
  out_dir: outputs
  save_best: true
  log_interval: 50
